CONFIG_OS="linux"
CONFIG_ARCH="amd64"
CONFIG_BUILD_MODE="Debug"
CONFIG_EXTRA_LDFLAGS=""
CONFIG_DIRECTOR_NAME="tlsthing-director"
CONFIG_CLIENT_NAME="tlsthing-client"
CONFIG_DEBUG_LEVEL="3"
CONFIG_PORT="2443"
